#ifndef GENERIC_EXPRESS_INSTANCE_PARSER_GLOBAL_H
#define GENERIC_EXPRESS_INSTANCE_PARSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GENERIC_EXPRESS_INSTANCE_PARSER_LIBRARY)
#  define GENERIC_EXPRESS_INSTANCE_PARSER_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define GENERIC_EXPRESS_INSTANCE_PARSER_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif //GENERIC_EXPRESS_INSTANCE_PARSER_GLOBAL_H
